---
output: 
  bookdown::pdf_document2: default
  distill::distill_article: default
title: "Locating Czech Constitutional Court Decisions in Doctrine Space and Measuring its Caselaw Consistency"
abstract: "Our research explores the estimation of positions of Czech Constitutional Court decisions in a doctrine space using Bayesian statistical model. Traditional methods of estimating ideological positions suffer from limitations, prompting the adoption of new text-as-data approaches empowered by advances in computational technology and statistics. Two research teams have attempted to overcome previous constraints and estimate judicial positions more accurately, one in the SCOTUS context and one in the German lower courts context. Our study implements the method of Clark and Lauderdale of estimating the locations of SCOTUS decisions with positive or negative references to its caselaw: the closer decisions are to each other, the more likely they are to cite themselves positively and vice-versa. We combine our own dataset of all CCC decisions with the data on citations provided to us by Beck. We use the programming language R and the Bayesian engine Stan to estimate the positions employing the Bayesian model of Clark and Lauderdal. Estimating the positions allows us to examine the consistency of the CC's case law across different senates and the plenum. We narrow our analysis to areas of law in common doctrine space that are prone to inconsistency, namely restitution cases and costs of civil proceedings. The research contributes to harnessing the potential of machine learning and quantitative methods in legal research and clarifies the factors influencing caselaw consistency."
author: 
  - Štěpán Paulík, Humboldt Universität zu Berlin, Institut für Sozialwissenschaften^[stepan.paulik.1@hu-berlin.de]
  - Jaromír Fronc, Charles University, Faculty of Law^[jaromir.fronc@gmail.com]
keywords: "empirical legal research, courts, dissents, judicial behavior, political science, Bayesian statistics, regression analysis"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontsize: 11pt
doublespacing: TRUE
endnote: no
indent: true
link-citations: yes
linkcolor: blue
# pandocparas: TRUE
sansitup: FALSE
header-includes:
  - \usepackage{longtable}
  - \LTcapwidth=.95\textwidth
  - \linespread{1.05}
  - \usepackage{hyperref}
  - \usepackage{float}
bibliography: "`r rbbt::bbt_write_bib(path = 'bibliography.bib', overwrite = TRUE, library_id = rbbt::bbt_libraries()$id[rbbt::bbt_libraries()$name == 'location_consistency'])`"
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Introduction
The question of to what extent is court case law consistent has been of interest of legal scholarship as well as legal practice for quite some time.
While the question has been posed in the context development of caselaw over time, in the case of SCOTUS, or in the comparison between differing courts, such as Germany's lower courts, we believe it to be equally applicable to collegial courts organised into multiple chambers, such as ECHR, CJEU or national apex (supreme and constitutional) courts.
While works about caselaw consistency are typical doctrinal, presenting examples of mutually incompatible decisions, we study caselaw consistency empirically employing quantitative methods.

In our article, we deploy the scaling model of [@clarkLocatingSupremeCourt2010] to test whether it works outside the US context and to attempt to measure the consistency of CCC's case-law. "Given the centrality of theories of judicial policymaking to various substantive problems in political science, the method of scaling opinions developed in this article can facilitate a range of future research."

The purpose of applying the Clark model is to estimate the legal position taken by a given opinion, notwithstanding its outcome, i.e. notwithstanding its disposition. 

# Theory

The issue of estimating caselaw consistency effectively boils down to two issues: firstly, the estimation of location of a case in a case-space and, secondly, to quantitatively conceptualizing consistency of caselaw.
In both aspects, we build on previous work - on the empirical development of estimating location of a judicial decision in a common case-space [@kornhauserModelingCollegialCourts1992a; @kornhauserModelingCollegialCourts1992; @laxNewJudicialPolitics2011] and theoretical work into consistency law across court chambers [@fjelstulHowChamberSystem2023].

In the Czech legal system, there is not a precedent system *per se* comparable to the common law legal systems. However, the judges are still required to provide reasons for their judgments - often done in a way of citing other court decisions. The decision which legal sources to cite, which not to cite and how to cite them does not happen haphazardly. In line with the empirical studies on the role of precedent, we argue that the judges behave strategically in the sense that they care about the compliance with their decision. Second, the CCC judges find their decisions more persuasive if "legal consistency can be demonstrated across time and place". Third, the compliance with the CCC judgments is affected both by the lower courts' behavior as well as the other branches of power. Lastly, the embedding of decisions into the net of caselaw imputes time and effort costs on the CCC judges, who, therefore, have to make the decisions as to which cases to cite and which not to cite [@lupuPrecedentInternationalCourts2012]. Citing other CCC decisions enables the CCC justices to explain their conclusions and reasoning as well as to embed the decision within the network of other decisions. It also follows that not all references are the same: the judges can reference other decisions positively, whenever the cited decision and its reasoning is similar, and negative, whenever it is dissimilar.

## Locating court decisions

Traditionally mainly American empirical legal science has long tried to estimate a position of judges or judicial decisions, especially in the context of political ideology of SCOTUS (Supreme Court of the United States) decisions and judges.
Based on this estimation, the research sought to answer subsequent sociological research questions.
Spaeth-Segal [@segalIdeologicalValuesVotes1995] and Martin-Quinn [@martinDynamicIdealPoint2002] scores are among the examples of attempts to quantify the ideological position of judgments or judges.
However, these traditional estimation methods suffer from various shortcomings, such as measuring ideological positions indirectly (based on the party the decision was made against) or using data not available outside the American context (information about judges' voting) and, thus, making the research near impossible to replicate elsewhere.

Recent developments in information technology enable more precise and diverse work with data, specifically with text of court decisions as data.
This progress is starting to make its way into social and legal sciences outside the US as well, the first issue of the recently released European Journal on Empirical Studies proves this point [@bhupatirajuMappingGeometryLaw2024; @chauComputationalLegalStudies2024]. Two research teams have utilised the progress to overcome the aforementioned limitations in traditional estimation efforts of judicial decisions and judges' positions.

Both models rest on the assumption that a location of a court decision can be estimated based on its relationship to other court decisions and sources of law.
Courts typically justify their conclusion by reference to other court decisions or laws that are typically close to them in a case-space.
Both teams make the following assumptions (a) each opinion has a fixed location along a single latent dimensions delimited by a common case-space and (b) they assume a proximity relationship, i.e. the probability of a (positive) reference to a court decision or other sources of law increases the closer the decisions are to each other in a case-space [@clarkLocatingSupremeCourt2010; @arnoldScalingCourtDecisions2023].

The exact understanding of the relationship between a reference between two decisions and their position on the latent dimension can be understood in two manners.
According to Clark and Lauderdale, *directional models* assume "that an opinion is more likely to cite a precedent if the precedent has the same [ideological] polarity as the opinion", whereas *proximity models* assume that "the probability of a positive citation from an opinion to a precedent decreases as the doctrine between the two opinions diverges." [@clarkLocatingSupremeCourt2010, p. 875].
Both studies, upon which we build, ultimately base their model on the proximity model for it better reflects the assumed practice of citing court decisions: "Given the choice between two precedents with identical doctrine and differing directional outcomes, we believe that a justice in this situation would cite both precedents positively." [@clarkLocatingSupremeCourt2010, p. 875] Moreover, the proximity model better corresponds to the recent shift to model court decisions in a case-space. Thus, we do not diverge from the original studies.


## Case-space model
In order to be able to scale the legal position of court decisions, the set of cases must fall within the same case-space. We now move on to the understanding and relevance of a case-space model.

The case-space model was developed in an attempt to model the idiosyncrasies of court decision-making, i.e. that a court is a body resolving disputes, cases. Its starting point is that the idea of a case must be taken seriously: we must be able to represent a case and what rendering a judgment in any case means. In contrast to legislative models, "judicial preferences and goals are structured by the choices available to judges: dispositions and the rules that denote general sets of case dispositions. The second is that judicial choices, rule creation, and rule application are deeply affected by collegial and hierarchical (horizontal and vertical) divisions of power." [@laxNewJudicialPolitics2011] Thus, the case-space model incorporates into itself legal rules, the judges' preference towards them, as well as the facts of the case.

More specifically, the way to represent a case is by locating it in a space of possible cases, the case-space. A case then denotes a "legally relevant event that has occurred" out of many that could have occurred. A car in a 30km/h zone could have in one case gone 28 km/h or in another 32 km/h. Both possibilities represent a case of a set of cases on the common case-space. A legal rule is, then, a partition of the case-space into whoever wins and whoever loses the case. However, where exactly the legal rule cuts across the case-space is determined by the judges' preferences towards the legal rule. As @laxNewJudicialPolitics2011 puts it, battles over law are struggles over partitions of the case space. The disposition of the case then refers to which party wins the case.

It is obvious that the real judicial adjudication is not as simple as a clear cut speeding rule. Typically, in order to resolve a case, the judges need to map the available evidence to the legal facts and then they have to select and interpret an appropriate legal rule to apply. Both processes are naturally subject to human judgment [@cameronChapterWhatJudges2017]. The indeterministic nature of this mapping opens up ways for disagreement. @landaDisagreementsCollegialCourts2007 draw multiple theoretical sources of disagreement from the case-space model. The first and clear source of disagreement among judges is that about facts. Different judges may place the facts of the case in the case-space differently. There are other sources of disagreement: which dimensions should be relevant under any given legal rule to determine the disposition of a case, disagreement about "thresholds" within dimensions, and a couple of more sources of disagreement, which all can be summarized as a disagreement about the legal rule. All these sources of disagreement may lead to inconsistency across judges and chambers. If one judge views the facts of the case differently from others, a different chamber composed of different judges may not reach the same conclusion given the same set of legally relevant facts. The same applies to judges' preferences over legal rules.



For the sake of simplicity, the case-space is a uni-dimensional space, a line, with the specific case being a scalar on that dimension.

To dispose of the case, the judge

## Case-law consistency

### Theoretical conceptualization and operationalization of case-law consistency

We now move on to elucidating how we understand the term *consistency* of case-law or of *a court's application of the law* [@fjelstulHowChamberSystem2023, p. 2].
Our understanding is firmly rooted in and builds upon the definition provided by Fjelstul in his theoretical study of the chamber system at the Court of Justice of the European Union (CJEU).
Therein, Fjelstul theoretically conceptualizes *consistency* "as the degree to which the disposition of a case would change if it were decided by a different chamber" of a court.

Fjelstul operationalizes the theoretical definition as "the variance of the distribution of the expected probability that the plaintiff wins a case across counterfactual chambers" [@fjelstulHowChamberSystem2023, p. 2] Put differently, an application of law before a court is consistent only if a court would reach the same conclusion in the same case with the same party, regardless of its composition or the deciding formation.

In theory, both the theoretical definition and operationalization are counter-factual as we can never observe how any given decision would be decided by more than one actual court chamber.
We can, however, attempt to measure the trend across general population of cases falling into one case-space.
And while we are aware that comparison based on observational data is not conclusive of any causal relationship, our ambition is only to offer a descriptive analysis of the CCC's caselaw without necessarily uncovering any causal relationship in the sense of *what type of underlying feature leads to higher/lower consistency of CCC's caselaw?*

Fjelstul’s operationalization of consistency assumes variation of chambers in a given point of time. Therefore, it also implicitly assumes that the legal situation is unchanged. If two chambers were to decide the same case at the same time differently, we might legitimately “see the judicial process as arbitrary or capricious” [@fjelstulHowChamberSystem2023, p. 2].

However, a court’s case law may also evolve in time. Although we may regard this process as undesirable too, it is almost inevitable in a large span of time with changing political and societal attitudes – or with changing the court’s composition. Therefore, looking at a totally disciplined court that respects its case law until the appropriate chamber (plenary, grand chamber) overturns it explicitly, we could describe its decision making as consistent in a given point of time (per Fjelstul’s definition), but still inconsistent in a span of time.

Thus, modeling consistency with a case dataset must take into consideration that the cases were decided at various points of time. This fact may distort the results, but at the same time, it enables us to study whether the case law has moved in any direction in a process of time. It can also help us to study the caselaw evolution through ignoring, distinguishing, limiting and explicitly rejecting earlier rulings. @spriggsExplainingOverrulingSupreme2001, p. 1104 conclude that previous negative treatment of a precedent significantly increases the risk of its future overruling. Similarly, @reddickNormViolationLower2000 show that lower courts may detect the case space direction SCOTUS is taking and even anticipate overruling its precedent.
If that is the case, we should see in a given case space that decisions are incrementally moving in a certain direction, as opposed to one “big” decision that would make the switch. This may be even more visible in the institutional setting where only a designated court body (such as plenary session of the supreme court) can explicitly overrule precedent; then, such overruling will be probably preceded by past negative treatment (or ignorance) of the court’s individual chambers and/or lower courts.

### The CCC and its case-law inconsistency
The objective of our contribution is to present research in which we apply Clark and Lauderdale's method to the Czech Constitutional Court. We believe their approach is more suitable for the institutional setup of the CCC, where decisions refer primarily to its own case law [@harastaCitacniAnalyzaJudikatury2021, p. 220] and references to legal provisions are not as diverse (Constitution, Charter of Fundamental Rights and Freedoms).

Based on the estimated positions of Constitutional Court decisions, we will examine primarily the consistency of the Court's case law across senates and the plenary.
The interplay between the consistency of case law and a court's internal structure has already been the subject of quantitative empirical research in the context of the Court of Justice of the European Union [@fjelstulHowChamberSystem2023], which we build upon.

The CCC is widely regarded as one of the most powerful constitutional courts in the world [@kosarConstitutionalCourtCzechia2020, p. 143; but see @sipulovaCzechConstitutionalCourt2018, p. 56, concluding that this claim is not fully supported by empirical data]. It is made up of 15 justices who are divided into four 3-member senates (plus the President and two Vice Presidents). Similarly to SCOTUS, the justices are appointed by the president of the Czech Republic with the advice and consent of the Senate.
The bulk of the CCC’s work is represented by individual constitutional complaints, which are, as a rule, decided upon by the senates; the judge rapporteur may declare certain complaints as inadmissible. The CCC decides in plenary sessions (*en banc*) mainly on review of primary and secondary legislation.
The CCC rules in a form of a judgment (*nález*) and a decision in a narrow sense (*usnesení*). A vast majority of the CCC cases are decided in the form of decision. As a legal rule, the CCC must respect its own case law, but only in the form of judgment [@kosarConstitutionalCourtCzechia2020, p. 161-163]. A senate is obliged to submit a case to the plenary if it wants to overrule existing case law.
From that follows that each 3-member senate might develop its “own” caselaw which will be binding to all state bodies including the CCC itself. In theory, this (mal)practice is restricted by the necessity (mentioned above) of submitting cases to the plenary. However, that requires certain level of diligence and discipline on the side of the senates. It also does not prevent the senate from developing whole “new” caselaw, distinguishing from earlier precedents if necessary.
Justices may write dissenting and concurring opinions, but it is also possible to vote against the majority opinion without dissenting. From that follows that dissenting opinions (which are publicly available) are an incomplete indication of disagreement within the CCC. That is seen by most authors as a major methodological problem in the empirical research of the CCC justices [@smekalDeterminantsJudicialDecisionmaking2020, p. 126-127, @chmelCoOvlivnujeUstavni2021, p. 166, @vartazaryanSitovaAnalyzaDisentujicich2022, p. 1196-1197]. However, it can still be interfered from the “dissenting coalitions” that there was a clear division between two groups of justices in the CCC’s last decade [@vartazaryanSitovaAnalyzaDisentujicich2022, p. 1209-1211]. This division defies simple categorization along ideological lines but one possible explanation is that some justices are more activist in the sense of willingness to develop new case law [@chmelCoOvlivnujeUstavni2021, p. 162].

Scholarly literature is basically unanimous [@bobekJudikaturaPravniArgumentace2013] in the notion that the case law of the Constitutional Court is inconsistent due to the massive number of constitutional complaints [cf. @kosarConstitutionalCourtCzechia2020, p. 153], diffusion of decision-making bodies [cf. @kosarConstitutionalCourtCzechia2020, p. 154-155; @vyhnanekJudikaturaUstavnimPravu2023, p. 15] and the conscious or unconscious failure to unify the case law. The 3-member senates either are unaware of conflicting case law, ignore it, or employ tricks to avoid its binding nature.

In the 3-member senate, the identity of judge rapporteur has such a significant effect on the probability that a constitutional complaint will be successful [@chmelCoOvlivnujeUstavni2021, p. 106-128] that the random assignment of judge rapporteur can be fittingly described as “lottery” [@chmelCoOvlivnujeUstavni2021, p. 129]. However, that itself does not imply...

Literature also provides examples of areas where the Constitutional Court's decision-making practice is particularly inconsistent.
It can be assumed that the level of inconsistency may be related to the value-based or legal-political dimension of the issue, which causes different judges to tend to decide differently.

The area of restitutions is widely considered to be one of the most disputed legal-political issues after the 1989 Velvet Revolution related to transitional justice, appearing many times before the CCC [@biagiEuropeanConstitutionalCourts2020, p. 165-167]. It is also frequently mentioned as the prime example of CCC’s inconsistency [@bobekJudikaturaPravniArgumentace2013, p. 363; @vyhnanekJudikaturaUstavnimPravu2023]. Surprisingly, restitution litigation was not restricted to the 1990s, often spanning decades – the neverending presence of the issue also helped by the restitution of church property enacted only in 2012 after a heated political and legal debate.

Vertical separation of powers is an issue where the CCC’s case law has evolved over time. The CCC has relaxed the limits placed on the legality of ordinances of territorial self-governing units (regions and municipalities) [@kosarConstitutionalCourtCzechia2020, p. 148]. Among the CCC justices, this issue remains controversial up to present time.

# Method
Regarding the method, we employ a mix of quantitative methods (Bayesian statistics) and legal computational studies. First, we narrow down the selection of decisions to those falling under the given issues based on the subject matter index. With access to data from the Beck-online database, we can subsequently identify mutual citations in the Constitutional Court's case law. The data on mutual citations includes the information whether the citation was positive or negative (overruling, distinguishing). The prepared data are then fed into the Clark and Lauderdale's Bayesian model using the available code to replicate their research.
But we use the more modern RStan as the Bayesian environment instead of RJags to simulate the Markov Chains Monte Carlo: "Stan's MCMC techniques are based on Hamiltonian Monte Carlo, a more efficient and robust sampler than Gibbs sampling or Metropolis Hastings for models with complex posteriors." [@brooksHandbookMarkovChain2011]

## Model selection and specification
At first, we stood before a choice between two scaling models developed by @clarkLocatingSupremeCourt2010 and @clarkEstimatingEffectLeisure2018 for the same purpose: estimation of a location of a court decision in a given case-space. Both models share certain theoretical assumptions but diverge on practical implementation.

Both models are based - at least implicitly - on the item response theory (IRT). In psychometrics, the IRT is employed to model "the probability of an examinee responding to an item response given their level of a latent variable(s) of interest" [@wellsItemResponseTheory2021]. The model estimates the probability of answering a question correctly given certain underlying latent variable, the ability of the examinee for example.^[For an interesting application to estimate the fairness of examination at law faculties, see @hufeldJedeKorrekturAndere2024] The IRT enables the researchers to take into account features such as the item difficulty, item discrimination or a pseudo-guessing parameter. Its two main advantages are that given that assumptions of the model have been met, the IRT can efficiently estimate even a large number of parameters using Bayesian Markov Chain Monte Carlo (MCMC), and that the item parameter values (its difficulty or discrimination) do not depend on the person parameter values (their latent ability) [@wellsItemResponseTheory2021].

Much of the political science on (point) estimating political positions of legislators based on roll-call data [@jackmanMultidimensionalAnalysisRoll2001a; @clintonStatisticalAnalysisRoll2004] or on their twitter usage [@barberaBirdsSameFeather2015] is based on the IRT. The extension of IRT to the political space is based on the idea that certain response (a vote in the Parliament or the decision to follow someone on Twitter) is known and that it can be used to estimate the latent variable of the person, such as their political stance. In the latter study, @barberaBirdsSameFeather2015 estimated the position of political actors as well as ordinary Twitter users based on their decision to follow or not to follow other accounts. In a simple uni-dimensional (from the perspective of the latent variable) without the guessing parameter, the IRT model is as follows:

$$ P(u_{i,j} = 1|\theta_{j}, \alpha_{i}, \beta_i) = \frac{\exp(\alpha_i(\theta_j - \beta_i))}{1 + \exp(\alpha_i(\theta_j - \beta_i))} $$
Where $u_{i,j}$ is the item response for the person *j* on item *i*, $\theta_j$ is the latent variable of interest - the point estimate, $\alpha_i$ and $\beta_i$ represent the idem parameters - its discrimination and its difficulty. The model is a logistic model as it follows the $\frac{exp(X)}{1+exp(X)}$ structure of a logistic function. Logically, the closer the ability of the examinee to the difficulty of the item, the more likely is then the correct response. What if, however, the $\beta$ was defined as $\theta$ of another person? That is exactly what the @barberaBirdsSameFeather2015, @clarkLocatingSupremeCourt2010 and @arnoldScalingCourtDecisions2023 studies do. They rely on the idea that based on knowing the item response, i.e. whether two users followed each other or whether one court decision cited another, we can replace the term $(\theta_j - \beta_i)$ with the distance between the location of two persons, i.e. court decisions, such as the distance between the location of decision *i* $\theta_{i}$ and location of another decision *j* $\phi_j$ equals to their Euclidean distance $||(\theta_i - \phi_j)||^2$. The MCMC algorithm then iterates draws from the posterior distribution long enough to estimate the location of all decisions fed to the model.

The two models differ as to what they consider to be the item response. In the @clarkLocatingSupremeCourt2010 study, the item response is whether a court decision cited another positively, whereas in the @arnoldScalingCourtDecisions2023 study, the item response is whether a court decision at all referred to another legal source. More specifically, @clarkLocatingSupremeCourt2010 examine SCOTUS, which, like the Czech Constitutional Court, primarily cites its own decisions [@clarkLocatingSupremeCourt2010]. They consider only these citations, which they further divide into positive and negative based on their relationship to the cited decision. More specifically, the authors collected all freedom of religion and search and seizure cases and then manually annotated citations among those decisions as either positive and negative. The estimation was based on such an encapsulated, self-referential dataset and on the citations being either positive or negative. In contrast, @arnoldScalingCourtDecisions2023 study German general courts of lower instances, their focus was not the highest *Bundesverfassungsgericht* but the consistency of caselaw on the state level of the judiciary. Ordinary lower courts typically refer to various legal provisions and decisions of other courts [@arnoldScalingCourtDecisions2023]. Hence, they only use information about references to other legal texts, which can include not only decisions of the same court (as in the case of SCOTUS) but also provisions of any legal regulation or decisions of any court.

The feature selection of the two models is justified by the nature of typical citations on the highest level of the judiciary - SCOTUS or constitutional courts - and on the lower levels of ordinary judiciary. The caselaw citations of SCOTUS or constitutional courts are typically self-referential. Citations of laws typically refer to vague constitutional provisions, which will be typically shared by cases on both extremes on a latent dimensions, and as such do not contain any information as to the location of the decision on the latent dimensions. In contrast, a lower court decision will typically cite decisions of higher courts and very precisely formulated legal provisions. In practice, a conservative freedom of speech decision will refer to the same vague and broadly-formulated provisions as a progressive freedom of speech decision, whereas strict lower court defamation decisions will altogether refer to different legal provisions than lenient defamation decisions.

@clarkLocatingSupremeCourt2010 also make use of data on the estimated ideology of the SCOTUS justices. We do not have such data as the CCC justices generally do not display such clear political positions. Additionally, the CCC is made up predominantly of appointees of the same president at any given time [@smekalDeterminantsJudicialDecisionmaking2020, p. 128]. However, we show that such data are not decisive for the model results.

## Data
To apply the model, we used data from the CCC database [@paulikCzechConstitutionalCourt2024] and metadata provided by the Beck-online database. The official CCC database *NALUS*^[Available at: https://nalus.usoud.cz/] consists of the texts of all CCC decisions and accompanying metadata (such as dates, judge rapporteur, registry items, relevant legal provisions).
 
To identify relations between the decisions, we use metadata that was kindly provided by the Czech legal information system *Beck-online*^[Available at: https://www.beck-online.cz/] owned by the C. H. Beck publishing house. In this respect, we follow the approach of both @clarkLocatingSupremeCourt2010 (using Shepard’s citation data) and @arnoldScalingCourtDecisions2023 (using data by the German legal database Juris). Beck-online captures court decisions cited by another decision, together with the “quality” of the citation, i.e. capturing the court’s treatment of the decision cited. This type of metadata is similar to *Shepard's Citations* used by the U.S. legal databases but pretty rare in the European markets.

Beck-online uses a total of eight types of quality (in addition, some citations may not be annotated with quality yet); these are displayed to users in the metadata of the citing and cited decision. Citation metadata capture only decisions cited by the court itself and only as a part of court’s argumentation. That approach excludes decisions mentioned solely by parties or in procedural context only. One type of quality indicates that the decision is cited by a dissenting (or concurring) opinion, which leaves us with seven qualities describing the attitude of the majority opinion. To simplify the input data in the vein of Clark and Lauderdale, we flatten these seven qualities into two: positive or negative.

# Results
